on:
  push:
  pull_request:

name: build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: leanprover/lean-action@v1
        with:
          check-reservoir-eligibility: false

      # Run executable example as described in README
      - run: test/run_executable_example.sh
