on:
  push:
  pull_request:

name: build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: leanprover/lean-action@v1
        with:
          check-reservoir-eligibility: false
  run_executable:
    steps:
      - pwd
      - tree
      - echo "8875913 1124087 165048 20902 185856 26055 3456 484\n1776924" | .lake/build/bin/formalqkd > output.txt
      - if cat output.txt | grep -q 'SKL = 1464719'; then
          echo "matched"
        fi
